// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmbdhegjgqsuuhyinmsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtYmRoZWdqZ3FzdXVoeWlubXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDYzMTYsImV4cCI6MjA3Mzg4MjMxNn0.8SiAWptx5mh-CJC1da9iJaTlzzTkN1BghsBlFg3JkUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});